### Import Libraries

In [1]:
import numpy as np
import cv2
import os
import random
import matplotlib.pyplot as plt



### Load Dataset

In [2]:
DIRECTORY = r'C:\Users\Lenovo\Downloads\archive (18)\Car-Bike-Dataset'
CATEGORIES = ['Bike', 'Car']

### Data Preprocessing(Read Images Converted Into Numpy Array Using opencv)

In [3]:
IMG_SIZE = 128
data = []
for category in CATEGORIES:
    folder = os.path.join(DIRECTORY, category)
#     print(folder)
    label = CATEGORIES.index(category)
#     loop through all the images
    for img in os.listdir(folder):
        img_path = os.path.join(folder, img)
#         print(img_path)
#         break
#         convert the images into array
        img_arr = cv2.imread(img_path)
        new_arr = cv2.resize(img_arr, (IMG_SIZE, IMG_SIZE))
        data.append([new_arr, label])
#         plt.imshow(new_arr)
#         break

In [4]:
len(data)

4000

In [5]:
random.shuffle(data)

In [6]:
data[0]

[array([[[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],
 
        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],
 
        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],
 
        ...,
 
        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],
 
        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],
 
        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
  

In [7]:
data[12]

[array([[[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],
 
        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],
 
        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],
 
        ...,
 
        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],
 
        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],
 
        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
  

In [8]:
X = []
y = []

for features, label in data:
    X.append(features)
    y.append(label)

In [9]:
len(X)

4000

In [10]:
len(y)

4000

In [11]:
X = np.array(X)
y = np.array(y)

In [12]:
X 

array([[[[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        ...,

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
        

In [13]:
y

array([1, 1, 0, ..., 1, 0, 0])

In [14]:
X = X/255
X

array([[[[1.        , 1.        , 1.        ],
         [1.        , 1.        , 1.        ],
         [1.        , 1.        , 1.        ],
         ...,
         [1.        , 1.        , 1.        ],
         [1.        , 1.        , 1.        ],
         [1.        , 1.        , 1.        ]],

        [[1.        , 1.        , 1.        ],
         [1.        , 1.        , 1.        ],
         [1.        , 1.        , 1.        ],
         ...,
         [1.        , 1.        , 1.        ],
         [1.        , 1.        , 1.        ],
         [1.        , 1.        , 1.        ]],

        [[1.        , 1.        , 1.        ],
         [1.        , 1.        , 1.        ],
         [1.        , 1.        , 1.        ],
         ...,
         [1.        , 1.        , 1.        ],
         [1.        , 1.        , 1.        ],
         [1.        , 1.        , 1.        ]],

        ...,

        [[1.        , 1.        , 1.        ],
         [1.        , 1.        , 1.        ]

In [15]:
# X = X.reshape(-1, 128, 128, 1)
# X

### Train  Test  Split

In [16]:

from sklearn.model_selection import train_test_split

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1,random_state=0)
print(len(X_train),len(y_train))
print(len(X_test),len(y_test))

print(X_train.shape,y_train.shape)
print(X_test.shape,y_test.shape)


3600 3600
400 400
(3600, 128, 128, 3) (3600,)
(400, 128, 128, 3) (400,)


In [18]:
y_test

array([1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,

### Build Convolution Neural Network

In [19]:
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Dense, Flatten

In [20]:
model = Sequential()

model.add(Conv2D(64, (3,3), activation = 'relu'))
model.add(MaxPooling2D((2,2)))

model.add(Conv2D(64, (3,3), activation = 'relu'))
model.add(MaxPooling2D((2,2)))

model.add(Flatten())

model.add(Dense(128, input_shape = X.shape[1:], activation = 'relu'))

model.add(Dense(1, activation = 'sigmoid'))

In [22]:
# model.summary()

In [23]:
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

In [24]:
history = model.fit(X_train, y_train, epochs=5, validation_split=0.1)

Epoch 1/5
102/102 [==============================] - 147s 1s/step - loss: 0.4545 - accuracy: 0.7926 - val_loss: 0.5141 - val_accuracy: 0.7833
Epoch 2/5
102/102 [==============================] - 149s 1s/step - loss: 0.1910 - accuracy: 0.9250 - val_loss: 0.3260 - val_accuracy: 0.8750
Epoch 3/5
102/102 [==============================] - 159s 2s/step - loss: 0.1221 - accuracy: 0.9568 - val_loss: 0.2624 - val_accuracy: 0.9028
Epoch 4/5
102/102 [==============================] - 158s 2s/step - loss: 0.0706 - accuracy: 0.9756 - val_loss: 0.2435 - val_accuracy: 0.9056
Epoch 5/5
102/102 [==============================] - 158s 2s/step - loss: 0.0456 - accuracy: 0.9843 - val_loss: 0.2428 - val_accuracy: 0.9222


In [ ]:
X_train.shape

In [ ]:
model.evaluate(X_test,y_test)

In [ ]:
plt.matshow(X_test[4])

In [ ]:
plt.matshow(X_test[5])

### Predict 

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
y_pred[0]

In [ ]:
y_pred[5]

### Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix , classification_report
y_pred = model.predict(X_test)
y_pred_classes = [0 if element < 0.5 else 1 for element in y_pred]

print("Classification Report: \n", classification_report(y_test, y_pred_classes))

In [ ]:
plt.plot(history.history['accuracy'], label='accuracy')
plt.plot(history.history['loss'], label = 'loss')
plt.xlabel('Epoch')
plt.legend(loc='lower right')
plt.show()

In [ ]:
3000/32

In [ ]:
2000/28